// lib/firebase_options.dart
//
// Dummy Firebase configuration for UI/testing.
// Replace these values with real Firebase configuration
// generated by `flutterfire configure` when the Firebase
// project is ready.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  /// Returns the Firebase configuration for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        return linux;

      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported on Fuchsia.',
        );
    }
  }

  /// Web Firebase configuration.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'dummy-web-api-key',
    appId: '1:000000000000:web:dummy-web-app-id',
    messagingSenderId: '000000000000',
    projectId: 'dummy-project-id',
    authDomain: 'dummy-project-id.firebaseapp.com',
    storageBucket: 'dummy-project-id.firebasestorage.app',
    measurementId: 'G-DUMMY000000',
  );

  /// Android Firebase configuration.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'dummy-android-api-key',
    appId: '1:000000000000:android:dummy-android-app-id',
    messagingSenderId: '000000000000',
    projectId: 'dummy-project-id',
    storageBucket: 'dummy-project-id.firebasestorage.app',
  );

  /// iOS Firebase configuration.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'dummy-ios-api-key',
    appId: '1:000000000000:ios:dummy-ios-app-id',
    messagingSenderId: '000000000000',
    projectId: 'dummy-project-id',
    storageBucket: 'dummy-project-id.firebasestorage.app',
    iosClientId: 'dummy-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.example.sokoLetuTz',
  );

  /// macOS Firebase configuration.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'dummy-macos-api-key',
    appId: '1:000000000000:ios:dummy-macos-app-id',
    messagingSenderId: '000000000000',
    projectId: 'dummy-project-id',
    storageBucket: 'dummy-project-id.firebasestorage.app',
    iosClientId: 'dummy-macos-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.example.sokoLetuTz',
  );

  /// Windows Firebase configuration.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'dummy-windows-api-key',
    appId: '1:000000000000:web:dummy-windows-app-id',
    messagingSenderId: '000000000000',
    projectId: 'dummy-project-id',
    authDomain: 'dummy-project-id.firebaseapp.com',
    storageBucket: 'dummy-project-id.firebasestorage.app',
  );

  /// Linux Firebase configuration.
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'dummy-linux-api-key',
    appId: '1:000000000000:web:dummy-linux-app-id',
    messagingSenderId: '000000000000',
    projectId: 'dummy-project-id',
    authDomain: 'dummy-project-id.firebaseapp.com',
    storageBucket: 'dummy-project-id.firebasestorage.app',
  );
}
